### ISSUE TITLE
Support for Kinesis

### ISSUE THREAD

**Issue by Nedvedyy** [thenativeweb/node-eventstore#108]
It would be good if event store supports kinesis?

**Comment by adrai** [comment]
Feel free to submit a PR ;-)

**Comment by OleTraveler** [comment]
With kenesis, you'd lose all your events > 7 days old.  Depending on your use case, dynamo to dynamo streams might be a good option.  Write to dynamo, read from dynamo streams and for history, read from dynamo directly.

**Comment by susannaroden** [comment]
Closed due to inactivity for multiple years.
