### ISSUE TITLE
Wrong Dispatch order

### ISSUE THREAD

**Issue by fabry00** [thenativeweb/node-eventstore#129]
I've a problem with the dispatch order of the events, this is my code:

```
this.es.useEventPublisher((evt, callback) => {
        // bus.emit('event', evt);
      console.log('3______', evt.payload);
      callback();
});
public consume(event: Event): void {
        console.log('1 ##########', event.payload);
        const streamId ='app';
        this.es.getLastEventAsStream(streamId, (err, stream) => {
            stream.addEvent(event);
            stream.commit((err1, streamCommit) => {
               console.log('2 ++++++++++++', streamCommit.eventsToDispatch);
          });
        });
}
```

The output of the previous code is this:

> 1 ########## STARTED
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
>   eventstore:eventdispatcher publish event... +10s
> 3______ STARTED
>   eventstore:eventdispatcher set event to dispatched... +0ms
>   eventstore:eventdispatcher undefined +1ms
> 2 ++++++++++++ undefined
>   eventstore:eventdispatcher publish event... +1ms
> 3______ LISTENING
>   eventstore:eventdispatcher set event to dispatched... +0ms
>   eventstore:eventdispatcher undefined +1ms
> 2 ++++++++++++ undefined
>   eventstore:eventdispatcher publish event... +0ms
> 3______ ANALYZING
> 

As you can see the order of the events  received by the function `useEventPublisher` is not the same:
expected: STARTED --> ANALYZING --> LISTENING . but I got: STARTED --> LISTENING --> ANALYZING

if I remove the `useEventPublisher` declaration I got:

> 1 ########## STARTED
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 1 ########## ANALYZING
> 1 ########## LISTENING
> 2 ++++++++++++ [ Event {
>     streamId: 'app',
>     aggregateId: 'app',
>     aggregate: undefined,
>     context: undefined,
>     streamRevision: 108,
>     commitId: '5af47c614429da3d7245fe4a',
>     commitSequence: 0,
>     commitStamp: 2018-05-10T17:07:45.123Z,
>     payload:
>      { header: [Object],
>        payload: 'LISTENING',
>        type: 'sadas' },
>     applyMappings: [Function: applyMappings],
>     id: '5af47c614429da3d7245fe4a0',
>     restInCommitStream: 0,
>     _id: '5af47c614429da3d7245fe4a0',
>     dispatched: false } ]
> 2 ++++++++++++ [ Event {
>     streamId: 'app',
>     aggregateId: 'app',
>     aggregate: undefined,
>     context: undefined,
>     streamRevision: 108,
>     commitId: '5af47c614429da3d7245fe48',
>     commitSequence: 0,
>     commitStamp: 2018-05-10T17:07:45.120Z,
>     payload:
>      { header: [Object],
>        payload: 'ANALYZING',
>        type: 'sadas' },
>     applyMappings: [Function: applyMappings],

Here the first event the I have in the `streamCommit.eventsToDispatch` array is LISTENING and not STARTED

What am I missing?

**Comment by adrai** [comment]
Can you create a test for this?

**Comment by susannaroden** [comment]
Closed due to inactivity for more than 1 year.
