### ISSUE TITLE
suggest to add typescript support

### ISSUE THREAD

**Issue by beenotung** [thenativeweb/node-eventstore#134]
It will be more helpful to pick up the library especially when the documentation is not updated.

I am working on this repo, but haven't fully declared the types when I'm still understanding the library.
https://github.com/beenotung/typestub-eventstore

**Comment by nanov** [comment]
Hi!

Those can be done in a separate repository, exactly like how it was done [here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/aa574d1aeea616b455518562e7f7fdac68e3d533/types/cqrs-domain/index.d.ts). I could try helping you with building those in case you have any issues, misunderstandings.

HINT : At least to have something to start with, you could inspect the JSDoc declarations.

**Comment by susannaroden** [comment]
Hey everyone 👋 

New maintainer here… we, i.e. @thenativeweb, have taken over the responsibility to maintain this module from @adrai, and I would like to give a little update on this issue:

We agree that TypeScript support would be a major benefit for this module, so one of the first things we are going to do is to migrate the code base to TypeScript, so we will automatically have types for this. This will take some time, but for now I am closing this issue.

If you have any questions or anything else, please feel free to re-open it, or to open a new one 😊
