### ISSUE TITLE
PostgreSQL data store

### ISSUE THREAD

**Issue by walling** [thenativeweb/node-eventstore#144]
Are there any plans to support PostgreSQL for storage?

**Comment by adrai** [comment]
We do very like accepting pull requests 😜

**Comment by johannesschobel** [comment]
how would we create such a postgres store? any "instructions" on this?

**Comment by nanov** [comment]
well, you can take a look at the [inmemory](https://github.com/adrai/node-eventstore/blob/master/lib/databases/inmemory.js) implementation which serves as a 'base' for the rest. Basically adding an adapter [here](https://github.com/adrai/node-eventstore/tree/master/lib/databases) should do the trick.

**Comment by susannaroden** [comment]
Closed due to inactivity for more than 1 year.
