### ISSUE TITLE
Replaying events to rebuild aggregates

### ISSUE THREAD

**Issue by kojuka** [thenativeweb/node-eventstore#148]
Loving this library but still pretty new to event sourcing.

I'm having a tough time replaying events to rebuild aggregates.  The issue I am having is that it keeps killing my pods on my cluster.  Seems as if rebuilding these aggregates is a pretty memory intensive process.  

Currently I loop through my aggregates and publish messages to rabbitmq to distribute the work of rebuilding.  This works pretty well except I keep having failed pods which makes me nervous about missed events/aggregates.

What I'm wondering is if anyone has tips on how to do this reliably and efficiently.

**Comment by adrai** [comment]
Can you describe a but more in detail how you are doing this? How does your setup look like? Which functions do you call? How many events are you replaying?
How dows the “other” side look like? Do you use cqrs-eventdenormalizer?

**Comment by susannaroden** [comment]
Closed due to inactivity for more than 1 year.
