### ISSUE TITLE
low quality documentation

### ISSUE THREAD

**Issue by inf3rno** [thenativeweb/node-eventstore#38]
I think ppl (like me) who only know the basics, but never used an event storage in a project, won't understand how to use this lib, because the documentation is too low quality. It is just a bunch of examples without any indication why and when we should use the actual function.

**Comment by adrai** [comment]
I agree.

**Comment by ssipos90** [comment]
@inf3rno , I agree.
@adrai , maybe you could copy some bits from a project of yours and post them on the docs.
At this point, I've deciphered by trial and error.

**Comment by dynnamitt** [comment]
For one; should I as a noob start using JUST node-eventstore or should I look at one of the two "Consumers" .. what is a Consumer ?

**Comment by adrai** [comment]
it depends...
if you want to do event sourcing just start node-eventstore
if you want to do cqrs start with a "consumer"

**Comment by dynnamitt** [comment]
Thx . Back on track.

**Comment by susannaroden** [comment]
Hey everyone 👋 

New maintainer here… we, i.e. @thenativeweb, have taken over the responsibility to maintain this module from @adrai, and I would like to give a little update on this issue:

We agree that there is a strong need for a better documentation, and this will be one of the first things we are going to do with this repository. Hence, I am going to close this issue for now.

If you have any questions or anything else, please feel free to re-open it, or to open a new one 😊
