### ISSUE TITLE
Is there a way to get a list of unique aggregate id's?

### ISSUE THREAD

**Issue by danwkennedy** [thenativeweb/node-eventstore#69]
So we can be a little smarter about re-indexing our read models, it'd be cool if we could retrieve a list of unique aggregate ID's.

**Comment by mpseidel** [comment]
@danwkennedy how about just creating a new readmodel to store all aggregate ids (grouped by aggregate type or however you need it)?

**Comment by danwkennedy** [comment]
Seems counter-intuitive that a store for streams of events can't tell me how many streams are stored.

**Comment by mpseidel** [comment]
Yeah - would ne nice to have it out of the box. I think in this particular project the challenge is to support multiple db implementations which is already hard to do just to cater to the basic use cases. 
Have you used other even stores that have that capability?

**Comment by danwkennedy** [comment]
Agreed. GetEventStore at least has the capability in its management tools as far as I can tell. You can pull up a list of streams. I'm not sure if it's keeping track of them via internal event streams or not. That might be the design for this sort of feature: building a list of streams using the event streams themselves like you suggested @mpseidel

**Comment by mpseidel** [comment]
@danwkennedy yeah - geventstore ships with a bunch of projections if I remember correctly. Do you mind sharing what your plan to index your read models looks like assuming you had the list of unique aggregate ids?

**Comment by susannaroden** [comment]
Closed due to inactivity for multiple years.
