### ISSUE TITLE
Lambda, SNS, DynamoDB

### ISSUE THREAD

**Issue by tomdavidson** [thenativeweb/node-eventstore#73]
I am working on an event store implementation using AWS SNS, DynamoDB, and Lambdas. Understanding that a DynamoDB implementation would be needed, is there any reason why node-eventstore would be a bad fit? SNS vs Atom?

**Comment by adrai** [comment]
I think dynamodb should work...
Perhaps needing more indexes to fulfill all tests...

**Comment by adrai** [comment]
Would be nice to have a dynamodb implementation...
Feel free to submit a PR :-)

**Comment by tomdavidson** [comment]
Thanks for the quick reply. Still trying to get up to speed on all of the pieces, including your cqrs-domain.

**Comment by developmentalmadness** [comment]
I submitted a PR for dynamodb but build failed due to missing configuration for AWS. Any suggestions on how to successfully submit a PR? I could comment out the dynamodb type from the storeTest.js and eventstoreTest.js but that would be cheating :)

**Comment by adrai** [comment]
We need a sponsor...
or we skip it in the tests and run them only locally...

**Comment by developmentalmadness** [comment]
If you're fine with it I can just comment out the dynamo tests for the check-in.

**Comment by adrai** [comment]
Ok



Il giorno 4-ago-2016, alle ore 21:16, Mark J Miller <notifications@github.com<mailto:notifications@github.com>> ha scritto:


If you're fine with it I can just comment out the dynamo tests for the check-in.

-

**Comment by susannaroden** [comment]
Closed due to inactivity for multiple years.
