### ISSUE TITLE
Dispatcher doesn't dispatch sequentially

### ISSUE THREAD

**Issue by danwkennedy** [thenativeweb/node-eventstore#76]
If for whatever reason a large number of events don't get dispatched, the next time the dispatcher is started, it'll get the whole list of those events and call the callback in a loop. If you have some sort of async service using the dispatcher, a whole bunch of asynchronous requests will fire within milliseconds of each of them. It'd be nice if the dispatcher would wait for the passed callback to be called so event store doesn't overload other services downstream.

**Comment by adrai** [comment]
May you want to do a PR?

**Comment by susannaroden** [comment]
Closed due to inactivity for multiple years.
